name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  ubuntu-22-cmake-cpu-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Clone submodule
        id: clone_submodule
        run: |
          git submodule update --init --recursive

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install build-essential ninja-build

      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DLLAMA_NATIVE=OFF -DLLAMA_VULKAN=OFF -DCMAKE_BUILD_TYPE=Release
          ninja -j $(nproc)

  ubuntu-22-cmake-cpu-debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Clone submodule
        id: clone_submodule
        run: |
          git submodule update --init --recursive

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install build-essential ninja-build

      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DLLAMA_NATIVE=OFF -DLLAMA_VULKAN=OFF -DCMAKE_BUILD_TYPE=Debug
          ninja -j $(nproc)

  ubuntu-22-cmake-vulkan-release:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Clone submodule
        id: clone_submodule
        run: |
          git submodule update --init --recursive

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libvulkan-dev ninja-build

      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DLLAMA_NATIVE=OFF -DLLAMA_VULKAN=ON -DCMAKE_BUILD_TYPE=Release
          ninja -j $(nproc)

  ubuntu-22-cmake-vulkan-debug:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone
        id: checkout
        uses: actions/checkout@v4

      - name: Clone submodule
        id: clone_submodule
        run: |
          git submodule update --init --recursive

      - name: Dependencies
        id: depends
        run: |
          sudo apt-get update
          sudo apt-get install build-essential libvulkan-dev ninja-build

      - name: Build
        id: cmake_build
        run: |
          mkdir build
          cd build
          cmake .. -GNinja -DLLAMA_NATIVE=OFF -DLLAMA_VULKAN=ON -DCMAKE_BUILD_TYPE=Debug
          ninja -j $(nproc)